"use client";

import {
  useState,
  useRef,
  useCallback,
  useEffect,
  useMemo,
  type DragEvent,
  type ChangeEvent,
} from "react";
import { supabase, type SkipHistoryRow } from "@/lib/supabase";

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

interface LogEntry {
  time: string;
  msg: string;
  type: "info" | "success" | "error" | "data" | "process" | "warn";
}

/* ------------------------------------------------------------------ */
/*  Config                                                             */
/* ------------------------------------------------------------------ */

const BLACKLIST_COLUMNS = [
  "Transaction #",
  "Label #",
  "Pack",
  "Pack Size",
  "Normal UOM",
  "UOM2",
  "UOM 2",
  "U2 Qty",
  "U2 Quantity",
  "Generated by User",
  "Selection Method",
];

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

function ts() {
  return new Date().toLocaleTimeString([], {
    hour12: false,
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });
}

function cleanNameString(raw: unknown): string {
  if (!raw || raw === "undefined" || raw === "null") return "Unknown";
  const str = String(raw).trim();
  return str.replace(/^[0-9]+[\s\-:.]*/, "").trim() || "Unknown";
}

/* ================================================================== */
/*  COMPONENT                                                          */
/* ================================================================== */

export default function SkipTool() {
  /* ---- state ---- */
  const [file, setFile] = useState<File | null>(null);
  const [dragging, setDragging] = useState(false);
  const [logs, setLogs] = useState<LogEntry[]>([
    { time: ts(), msg: "Skip Report Tool v9.0 System Console", type: "info" },
  ]);
  const [indicator, setIndicator] = useState("_");
  const [elapsed, setElapsed] = useState(0);
  const [running, setRunning] = useState(false);
  const [timerDone, setTimerDone] = useState(false);

  const [tab, setTab] = useState<"console" | "history">("console");
  const [history, setHistory] = useState<SkipHistoryRow[]>([]);
  const [expandedSection, setExpandedSection] = useState<string | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const logBoxRef = useRef<HTMLDivElement>(null);
  const timerRef = useRef<number | null>(null);
  const startRef = useRef(0);

  /* ---- logging ---- */
  const log = useCallback(
    (msg: string, type: LogEntry["type"] = "info") => {
      setLogs((prev) => [...prev, { time: ts(), msg, type }]);
    },
    [],
  );

  useEffect(() => {
    logBoxRef.current?.scrollTo(0, logBoxRef.current.scrollHeight);
  }, [logs]);

  /* ---- timer ---- */
  const startTimer = useCallback(() => {
    startRef.current = performance.now();
    setRunning(true);
    setTimerDone(false);
    const tick = () => {
      setElapsed((performance.now() - startRef.current) / 1000);
      timerRef.current = requestAnimationFrame(tick);
    };
    tick();
  }, []);

  const stopTimer = useCallback(() => {
    if (timerRef.current) cancelAnimationFrame(timerRef.current);
    setRunning(false);
    setTimerDone(true);
  }, []);

  /* ---- file handling ---- */
  const handleFile = useCallback(
    (f: File) => {
      if (!f.name.toLowerCase().endsWith(".xlsx")) {
        log("Invalid file type. Please use .xlsx", "error");
        return;
      }
      setFile(f);
      log(`Input stream connected: ${f.name}`, "success");
      setIndicator("ready");
      setElapsed(0);
      setTimerDone(false);
      setTab("console");
    },
    [log],
  );

  const onDrop = useCallback(
    (e: DragEvent) => {
      e.preventDefault();
      setDragging(false);
      if (e.dataTransfer.files.length) handleFile(e.dataTransfer.files[0]);
    },
    [handleFile],
  );

  const onFileInput = useCallback(
    (e: ChangeEvent<HTMLInputElement>) => {
      if (e.target.files?.length) handleFile(e.target.files[0]);
    },
    [handleFile],
  );

  /* ================================================================ */
  /*  Supabase history                                                 */
  /* ================================================================ */

  const loadHistory = useCallback(async () => {
    try {
      const { data, error } = await supabase
        .from("skip_history")
        .select("*")
        .order("id", { ascending: true });
      if (error) throw error;
      setHistory(data ?? []);
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : "unknown error";
      log("Cannot load history: " + msg, "error");
    }
  }, [log]);

  useEffect(() => {
    if (tab === "history") loadHistory();
  }, [tab, loadHistory]);

  const saveToDB = useCallback(
    async (
      filename: string,
      slotCount: number,
      upcCount: number,
      topSlot: { name: string; score: number },
      topUpc: { name: string; score: number },
    ) => {
      try {
        const now = new Date();
        const { error } = await supabase.from("skip_history").insert({
          date: now.toLocaleDateString() + " " + now.toLocaleTimeString(),
          file: filename,
          slot: slotCount,
          upc: upcCount,
          top_slot: topSlot.name,
          top_upc: topUpc.name,
          top_slot_score: topSlot.score,
          top_upc_score: topUpc.score,
        });
        if (error) throw error;
        log("Stats & Champions saved to history.", "success");
        await loadHistory();
      } catch (e: unknown) {
        const msg = e instanceof Error ? e.message : "unknown";
        log("Failed to save history: " + msg, "error");
      }
    },
    [log, loadHistory],
  );

  const deleteEntry = useCallback(
    async (id: number) => {
      try {
        const { error } = await supabase
          .from("skip_history")
          .delete()
          .eq("id", id);
        if (error) throw error;
        await loadHistory();
      } catch {
        log("Failed to delete entry.", "error");
      }
    },
    [loadHistory, log],
  );

  /* ---- derived stats ---- */
  const stats = useMemo(() => {
    if (history.length === 0)
      return { total: 0, avgSlot: "0", avgUpc: "0" };
    const totalSlot = history.reduce((a, r) => a + (r.slot ?? 0), 0);
    const totalUpc = history.reduce((a, r) => a + (r.upc ?? 0), 0);
    return {
      total: history.length,
      avgSlot: (totalSlot / history.length).toFixed(1),
      avgUpc: (totalUpc / history.length).toFixed(1),
    };
  }, [history]);

  /* ---- leaderboards ---- */
  const leaderboards = useMemo(() => {
    const slotTally: Record<string, number> = {};
    const upcTally: Record<string, number> = {};
    history.forEach((item) => {
      const s = item.top_slot;
      const u = item.top_upc;
      if (s && s !== "N/A" && s !== "Unknown")
        slotTally[s] = (slotTally[s] || 0) + 1;
      if (u && u !== "N/A" && u !== "Unknown")
        upcTally[u] = (upcTally[u] || 0) + 1;
    });
    const sortT = (t: Record<string, number>) =>
      Object.entries(t)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 10);
    return { slot: sortT(slotTally), upc: sortT(upcTally) };
  }, [history]);

  /* ================================================================ */
  /*  Generate report                                                  */
  /* ================================================================ */

  const handleRun = useCallback(async () => {
    if (!file) {
      log("No file selected.", "error");
      return;
    }
    setLogs([]);
    setIndicator("processing...");
    startTimer();

    await new Promise((r) => setTimeout(r, 50));
    log("Initializing data pipeline...", "process");

    try {
      const ExcelJS = (await import("exceljs")).default;
      const buffer = await file.arrayBuffer();
      const workbook = new ExcelJS.Workbook();
      await workbook.xlsx.load(buffer);
      log("Binary loaded into memory.", "info");

      const worksheet = workbook.worksheets[0];
      if (!worksheet) throw new Error("Excel file is empty");

      log("Extracting and cleaning data...", "process");
      let headers: string[] = [];
      const rawData: Record<string, unknown>[] = [];

      worksheet.eachRow({ includeEmpty: true }, (row, rowNum) => {
        const values: unknown[] = [];
        row.eachCell({ includeEmpty: true }, (cell, colNum) => {
          values[colNum] = cell.value;
        });
        if (rowNum === 1) {
          headers = values.map((v) => (v ? String(v).trim() : ""));
        } else {
          const rowObj: Record<string, unknown> = {};
          let hasData = false;
          headers.forEach((h, i) => {
            if (h) {
              rowObj[h] = values[i];
              if (values[i] != null) hasData = true;
            }
          });
          if (hasData) rawData.push(rowObj);
        }
      });

      const cleanData = rawData.map((row) => {
        const newRow = { ...row };
        Object.keys(newRow).forEach((key) => {
          if (
            BLACKLIST_COLUMNS.some(
              (b) => b.toLowerCase() === key.toLowerCase(),
            ) ||
            !key ||
            key === "undefined"
          ) {
            delete newRow[key];
          }
        });
        return newRow;
      });
      log(`Processed ${cleanData.length} lines.`, "data");

      const sample = cleanData[0] || {};
      const empKey = Object.keys(sample).find(
        (k) =>
          k.toLowerCase().includes("generated by emp") ||
          k.toLowerCase().includes("generated by employee"),
      );
      const errorKey = Object.keys(sample).find(
        (k) =>
          k.toLowerCase().includes("error id") ||
          k.toLowerCase().includes("error type"),
      );

      if (empKey) {
        log(`Sorting by: ${empKey}`, "process");
        cleanData.sort((a, b) =>
          String(a[empKey] || "")
            .toLowerCase()
            .localeCompare(String(b[empKey] || "").toLowerCase()),
        );
      } else {
        log("Warning: 'Generated by Emp' not found. Sorting skipped.", "warn");
      }

      const slotSkips = cleanData.filter(
        (r) =>
          errorKey &&
          String(r[errorKey] || "")
            .trim()
            .toUpperCase() === "SKPSLT",
      );
      const upcSkips = cleanData.filter(
        (r) =>
          errorKey &&
          String(r[errorKey] || "")
            .trim()
            .toUpperCase() === "SKPLUPC",
      );
      log(`Total Slot Skips: ${slotSkips.length}`, "data");
      log(`Total UPC Skips: ${upcSkips.length}`, "data");

      const countStats = (dataset: Record<string, unknown>[]) => {
        const counts: Record<string, number> = {};
        dataset.forEach((r) => {
          const emp = cleanNameString(empKey ? r[empKey] : "Unknown");
          counts[emp] = (counts[emp] || 0) + 1;
        });
        const sorted = Object.entries(counts).sort((a, b) => b[1] - a[1]);
        return { top10: sorted.slice(0, 10), bottom10: sorted.slice(-10).reverse() };
      };

      const slotStats = countStats(slotSkips);
      const upcStats = countStats(upcSkips);

      const getLeaderData = (stats: { top10: [string, number][] }) => {
        if (!stats.top10 || stats.top10.length === 0)
          return { name: "Unknown", score: 0 };
        const valid = stats.top10.find((item) => item[0] !== "Unknown");
        if (valid) return { name: valid[0], score: valid[1] };
        return { name: stats.top10[0][0] || "Unknown", score: stats.top10[0][1] || 0 };
      };

      const topSlotData = getLeaderData(slotStats);
      const topUpcData = getLeaderData(upcStats);
      log(`Top Slot Skipper: ${topSlotData.name} (${topSlotData.score})`, "warn");
      log(`Top UPC Skipper: ${topUpcData.name} (${topUpcData.score})`, "warn");

      log("Saving statistics to database...", "process");
      await saveToDB(file.name, slotSkips.length, upcSkips.length, topSlotData, topUpcData);

      log("Generating Summary & Reports...", "process");
      await new Promise((r) => setTimeout(r, 10));

      const outWB = new ExcelJS.Workbook();

      /* ---- Summary sheet ---- */
      const createSummary = (
        slotTotal: number,
        upcTotal: number,
        slotTop: [string, number][],
        slotBottom: [string, number][],
        upcTop: [string, number][],
        upcBottom: [string, number][],
      ) => {
        const ws = outWB.addWorksheet("Summary", {
          views: [{ showGridLines: false }],
        });
        ws.properties.tabColor = { argb: "EC4899" };

        for (let r = 2; r <= 5; r++) {
          for (let c = 3; c <= 7; c++) {
            ws.getCell(r, c).fill = {
              type: "pattern",
              pattern: "solid",
              fgColor: { argb: "FFF1F5F9" },
            };
          }
        }
        ws.mergeCells("C2:G2");
        const title = ws.getCell("C2");
        title.value = "SKIP REPORT SUMMARY";
        title.font = { name: "Arial", size: 24, bold: true, color: { argb: "FF0F172A" } };
        title.alignment = { horizontal: "center", vertical: "middle" };
        ws.getRow(2).height = 40;

        ws.mergeCells("C4:G4");
        const metrics = ws.getCell("C4");
        metrics.value = `TOTAL SLOT SKIPS: ${slotTotal} | TOTAL UPC SKIPS: ${upcTotal}`;
        metrics.font = { size: 14, bold: true, color: { argb: "FF475569" } };
        metrics.alignment = { horizontal: "center", vertical: "middle" };
        ws.getRow(4).height = 30;

        const drawTable = (
          startColChar: string,
          startRow: number,
          tableTitle: string,
          titleColor: string,
          data: [string, number][],
        ) => {
          const startCol = startColChar.charCodeAt(0) - 64;
          ws.mergeCells(startRow, startCol, startRow, startCol + 1);
          const tCell = ws.getCell(startRow, startCol);
          tCell.value = tableTitle;
          tCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: titleColor } };
          tCell.font = { color: { argb: "FFFFFFFF" }, bold: true, size: 14 };
          tCell.alignment = { horizontal: "center", vertical: "middle" };
          tCell.border = { top: { style: "thin" }, left: { style: "thin" }, right: { style: "thin" }, bottom: { style: "thin" } };
          ws.getRow(startRow).height = 30;

          ["Employee", "Count"].forEach((h, i) => {
            const c = ws.getCell(startRow + 1, startCol + i);
            c.value = h;
            c.font = { bold: true, size: 12 };
            c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFE2E8F0" } };
            c.border = { top: { style: "thin" }, bottom: { style: "thin" }, left: { style: "thin" }, right: { style: "thin" } };
            c.alignment = { horizontal: "center", vertical: "middle" };
          });
          ws.getRow(startRow + 1).height = 25;

          data.forEach((item, i) => {
            const r = startRow + 2 + i;
            ws.getRow(r).height = 25;
            [item[0], item[1]].forEach((v, idx) => {
              const c = ws.getCell(r, startCol + idx);
              c.value = v;
              c.font = idx === 0 ? { size: 10 } : { size: 12 };
              c.fill = {
                type: "pattern",
                pattern: "solid",
                fgColor: { argb: i % 2 === 1 ? "FFF1F5F9" : "FFFFFFFF" },
              };
              c.border = { top: { style: "thin" }, bottom: { style: "thin" }, left: { style: "thin" }, right: { style: "thin" } };
              c.alignment = { horizontal: "center", vertical: "middle" };
            });
          });
        };

        drawTable("C", 8, "HIGHEST SLOT SKIPPERS", "FFDC2626", slotTop);
        drawTable("F", 8, "HIGHEST UPC SKIPPERS", "FFDC2626", upcTop);
        drawTable("C", 22, "LOWEST SLOT SKIPPERS", "FF16A34A", slotBottom);
        drawTable("F", 22, "LOWEST UPC SKIPPERS", "FF16A34A", upcBottom);

        ws.getColumn(3).width = 30;
        ws.getColumn(4).width = 15;
        ws.getColumn(6).width = 30;
        ws.getColumn(7).width = 15;
      };

      createSummary(
        slotSkips.length,
        upcSkips.length,
        slotStats.top10,
        slotStats.bottom10,
        upcStats.top10,
        upcStats.bottom10,
      );

      /* ---- Data sheets ---- */
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const addSheet = (name: string, rows: Record<string, unknown>[]) => {
        const sheet = outWB.addWorksheet(name);
        const keys = rows.length > 0 ? Object.keys(rows[0]) : [];
        if (keys.length === 0) return;
        sheet.columns = keys.map((k) => ({ header: k, key: k, width: 18 }));
        sheet.addRows(rows);
        sheet.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: keys.length } };
        const headerRow = sheet.getRow(1);
        headerRow.eachCell((cell: any) => {
          cell.font = { bold: true, color: { argb: "FFFFFFFF" }, size: 12 };
          cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF831843" } };
          cell.alignment = { vertical: "middle", horizontal: "center" };
        });
        sheet.eachRow((row: any, rowNum: number) => {
          if (rowNum === 1) return;
          row.eachCell((cell: any) => {
            cell.border = { top: { style: "thin" }, left: { style: "thin" }, bottom: { style: "thin" }, right: { style: "thin" } };
            cell.alignment = { vertical: "middle", horizontal: "center" };
          });
        });
        sheet.columns.forEach((col: any) => {
          let max = 10;
          col.eachCell?.({ includeEmpty: true }, (cell: any) => {
            const len = String(cell.value ?? "").length;
            if (len > max) max = len;
          });
          col.width = Math.min(max + 2, 40);
        });
      };

      if (cleanData.length > 0) addSheet("All Data", cleanData);
      if (slotSkips.length > 0) addSheet("Slot Skips", slotSkips);
      if (upcSkips.length > 0) addSheet("UPC Skips", upcSkips);

      const outBuffer = await outWB.xlsx.writeBuffer();
      const blob = new Blob([outBuffer], {
        type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      });
      const link = document.createElement("a");
      link.href = URL.createObjectURL(blob);
      link.download = `Skip_Report_${new Date().toISOString().slice(0, 10)}.xlsx`;
      link.click();
      URL.revokeObjectURL(link.href);

      stopTimer();
      log("Analysis Complete. Report Downloaded.", "success");
      setIndicator("idle");
    } catch (err: unknown) {
      stopTimer();
      const msg = err instanceof Error ? err.message : String(err);
      log(msg, "error");
      setIndicator("error");
    }
  }, [file, log, startTimer, stopTimer, saveToDB]);

  /* ================================================================ */
  /*  Render helpers                                                   */
  /* ================================================================ */

  const timerColor = running
    ? "text-sky-400"
    : timerDone
      ? "text-emerald-400"
      : "text-slate-300";

  const logColor = (type: LogEntry["type"]) => {
    switch (type) {
      case "success": return { text: "text-emerald-400", border: "#34d399", prefix: "OKAY" };
      case "error":   return { text: "text-red-400",     border: "#f87171", prefix: "FAIL" };
      case "data":    return { text: "text-sky-300",     border: "#38bdf8", prefix: "DATA" };
      case "process": return { text: "text-indigo-400",  border: "#6366f1", prefix: "EXEC" };
      case "warn":    return { text: "text-amber-400",   border: "transparent", prefix: "WARN" };
      default:        return { text: "text-slate-300",   border: "transparent", prefix: "INFO" };
    }
  };

  const LeaderBoard = ({
    title,
    data,
  }: {
    title: string;
    data: [string, number][];
  }) => (
    <div>
      <h4 className="text-xs uppercase font-bold text-slate-400 mb-3 tracking-widest">
        {title}
      </h4>
      {data.length === 0 ? (
        <div className="text-slate-600 italic text-xs">No data.</div>
      ) : (
        <div className="space-y-2">
          {data.map(([name, wins], i) => {
            const rankColor =
              i === 0
                ? "text-white"
                : i === 1
                  ? "text-slate-300"
                  : i === 2
                    ? "text-slate-500"
                    : "text-slate-400";
            const width = Math.min(100, (wins / data[0][1]) * 100);
            return (
              <div key={name} className="flex items-center gap-2 text-xs w-full">
                <span className={`font-bold w-4 text-right ${rankColor}`}>
                  #{i + 1}
                </span>
                <div className="flex-1">
                  <div className="flex justify-between mb-0.5">
                    <span className="font-medium text-slate-300 truncate">
                      {name}
                    </span>
                    <span className="text-slate-500">{wins}</span>
                  </div>
                  <div className="h-1.5 bg-slate-800 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-slate-500 transition-all duration-500"
                      style={{ width: `${width}%` }}
                    />
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );

  /* ================================================================ */
  /*  RENDER                                                           */
  /* ================================================================ */

  return (
    <div
      className="min-h-screen flex items-center justify-center p-4 sm:p-6"
      style={{ background: "#0f172a" }}
    >
      <div className="w-full max-w-7xl rounded-3xl p-6 sm:p-8 shadow-2xl bg-slate-800/70 backdrop-blur-xl border border-white/10">
        {/* ── Header ── */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-end mb-8 border-b border-slate-700 pb-6 gap-4">
          <div>
            <h1 className="text-4xl font-black tracking-tight text-white mb-1">
              SKIP <span className="text-sky-400">TOOL</span>
            </h1>
            <p className="text-slate-400 text-xs font-bold tracking-widest uppercase">
              By: Shane Cloonan
            </p>
          </div>
          <div className="hidden sm:flex flex-col items-end">
            <span className="text-[10px] text-emerald-500 font-mono font-bold tracking-widest uppercase mb-1 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              System Ready
            </span>
            <div
              className={`text-5xl font-black tracking-tight tabular-nums ${timerColor}`}
            >
              {elapsed.toFixed(2)}
              <span className="text-lg text-slate-500 ml-1 font-medium">s</span>
            </div>
          </div>
        </div>

        {/* ── Two columns ── */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8" style={{ height: 500 }}>
          {/* LEFT: Drop zone + button */}
          <div className="flex flex-col h-full gap-4">
            <div
              onClick={() => fileInputRef.current?.click()}
              onDragEnter={(e) => { e.preventDefault(); setDragging(true); }}
              onDragOver={(e) => { e.preventDefault(); setDragging(true); }}
              onDragLeave={(e) => { e.preventDefault(); setDragging(false); }}
              onDrop={onDrop}
              className={`flex-1 rounded-2xl flex flex-col items-center justify-center cursor-pointer group transition-all border-2 border-dashed ${
                dragging
                  ? "border-emerald-400 bg-emerald-400/5"
                  : "border-slate-600 bg-slate-900/40 hover:border-sky-400 hover:bg-sky-400/5"
              }`}
            >
              <div className="text-center pointer-events-none">
                <div
                  className={`w-20 h-20 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-lg transition-all ${
                    file ? "bg-emerald-500/10" : "bg-slate-800 group-hover:shadow-sky-500/20 group-hover:scale-110"
                  }`}
                >
                  {file ? (
                    <svg className="w-10 h-10 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  ) : (
                    <svg className="w-10 h-10 text-sky-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                    </svg>
                  )}
                </div>
                <h3 className="text-2xl font-bold text-white mb-2">
                  {file ? file.name : "Drop File Here"}
                </h3>
                <p className="text-slate-400 text-sm font-medium">.XLSX</p>
              </div>
              <input
                ref={fileInputRef}
                type="file"
                accept=".xlsx"
                className="hidden"
                onChange={onFileInput}
              />
            </div>
            <button
              type="button"
              onClick={handleRun}
              className="h-20 rounded-xl text-white font-black text-xl tracking-widest flex items-center justify-center gap-3 transition-all hover:-translate-y-0.5"
              style={{
                background: "linear-gradient(135deg, #38bdf8, #0284c7)",
                boxShadow: "0 4px 15px rgba(56,189,248,0.3)",
              }}
            >
              <span>GENERATE REPORT</span>
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </button>
          </div>

          {/* RIGHT: Console / History */}
          <div className="bg-[#0c1220] rounded-2xl border border-slate-800 overflow-hidden flex flex-col h-full">
            {/* Tabs */}
            <div className="grid grid-cols-2 border-b border-slate-800 bg-slate-900 shrink-0">
              {(["console", "history"] as const).map((t) => (
                <button
                  key={t}
                  type="button"
                  onClick={() => setTab(t)}
                  className={`py-3 text-xs font-bold uppercase tracking-widest transition-all border-b-2 ${
                    tab === t
                      ? "text-sky-400 border-sky-400 bg-sky-400/10"
                      : "text-slate-400 border-transparent hover:text-white hover:bg-white/5"
                  }`}
                >
                  {t === "console" ? "System Console" : "View History"}
                </button>
              ))}
            </div>

            {/* ── Console view ── */}
            {tab === "console" && (
              <div className="flex-1 flex flex-col overflow-hidden">
                {/* Mobile timer */}
                <div className="sm:hidden flex flex-col items-end p-3 border-b border-slate-800">
                  <div className={`text-4xl font-black tabular-nums ${timerColor}`}>
                    {elapsed.toFixed(2)}
                    <span className="text-base text-slate-500 ml-1 font-medium">s</span>
                  </div>
                </div>
                <div
                  ref={logBoxRef}
                  className="flex-1 overflow-y-auto p-4 font-mono text-xs text-slate-300 space-y-1"
                >
                  {logs.map((l, i) => {
                    const lc = logColor(l.type);
                    return (
                      <div
                        key={i}
                        className="py-1 pl-2.5"
                        style={{ borderLeft: `2px solid ${lc.border}` }}
                      >
                        <span className="text-slate-600 mr-2">[{l.time}]</span>
                        <span className="font-bold mr-2 text-xs opacity-70 w-8 inline-block">
                          {lc.prefix}
                        </span>
                        <span className={lc.text}>{l.msg}</span>
                      </div>
                    );
                  })}
                </div>
                <div className="p-2 px-4 bg-slate-900/50 text-xs text-sky-400 font-mono border-t border-slate-800 flex shrink-0">
                  <span className="mr-2">➜</span>
                  <span className="animate-pulse">{indicator}</span>
                </div>
              </div>
            )}

            {/* ── History view ── */}
            {tab === "history" && (
              <div className="flex-1 flex flex-col overflow-hidden">
                {/* Stats bar */}
                <div className="bg-slate-900/50 p-3 border-b border-slate-800 grid grid-cols-3 gap-2 shrink-0">
                  {[
                    { label: "Total Reports", value: stats.total },
                    { label: "Avg Slot Skips", value: stats.avgSlot },
                    { label: "Avg UPC Skips", value: stats.avgUpc },
                  ].map((s) => (
                    <div key={s.label} className="bg-slate-800 rounded p-2 text-center">
                      <div className="text-[10px] uppercase text-slate-500 font-bold">
                        {s.label}
                      </div>
                      <div className="text-lg font-bold text-white">{s.value}</div>
                    </div>
                  ))}
                </div>

                {/* Section toggles */}
                <div className="bg-gradient-to-b from-slate-950/90 to-slate-900/80 p-5 border-b border-slate-700/60 shrink-0">
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                    {[
                      { id: "topSkippers", label: "Top Skippers", color: "text-sky-300" },
                      { id: "dailyReports", label: "Daily Reports", color: "text-purple-300" },
                    ].map((sec) => (
                      <button
                        key={sec.id}
                        type="button"
                        onClick={() =>
                          setExpandedSection(
                            expandedSection === sec.id ? null : sec.id,
                          )
                        }
                        className="bg-gradient-to-br from-slate-900 to-slate-800 hover:from-slate-800 hover:to-slate-700 p-4 rounded-xl font-semibold transition-all flex items-center justify-between shadow-lg border border-slate-700/50"
                      >
                        <span className={`text-base ${sec.color}`}>
                          {sec.label}
                        </span>
                        <span
                          className={`text-lg transition-transform ${expandedSection === sec.id ? "rotate-180" : ""}`}
                        >
                          ▼
                        </span>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Top Skippers */}
                {expandedSection === "topSkippers" && (
                  <div className="bg-gradient-to-b from-slate-950/90 to-slate-900/80 border-b border-slate-700/60 p-5 overflow-auto max-h-[400px]">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <LeaderBoard title="TOP SLOT SKIPPERS" data={leaderboards.slot} />
                      <LeaderBoard title="TOP UPC SKIPPERS" data={leaderboards.upc} />
                    </div>
                  </div>
                )}

                {/* Daily Reports */}
                {expandedSection === "dailyReports" && (
                  <div className="bg-gradient-to-b from-slate-950/90 to-slate-900/80 p-5 overflow-auto max-h-[400px]">
                    {history.length === 0 ? (
                      <div className="p-8 text-center text-slate-600">
                        No history found.
                      </div>
                    ) : (
                      <div className="space-y-4">
                        {[...history].reverse().map((item) => {
                          const sDisplay =
                            item.top_slot && item.top_slot !== "Unknown" && item.top_slot !== "N/A"
                              ? `${item.top_slot} (${item.top_slot_score})`
                              : "N/A";
                          const uDisplay =
                            item.top_upc && item.top_upc !== "Unknown" && item.top_upc !== "N/A"
                              ? `${item.top_upc} (${item.top_upc_score})`
                              : "N/A";
                          return (
                            <div
                              key={item.id}
                              className="p-4 border-b border-slate-800 transition-all hover:bg-white/[0.03] border-l-2 border-l-slate-700 hover:border-l-sky-400 group"
                            >
                              <div className="flex justify-between items-start mb-2">
                                <div>
                                  <div className="text-xs text-slate-500 font-bold">
                                    {item.date}
                                  </div>
                                  <div className="text-xs text-slate-300 font-mono">
                                    {item.file}
                                  </div>
                                </div>
                                <button
                                  type="button"
                                  onClick={() => {
                                    if (confirm("Delete this record permanently?"))
                                      deleteEntry(item.id!);
                                  }}
                                  className="w-6 h-6 rounded flex items-center justify-center text-slate-600 hover:bg-red-500 hover:text-white transition-all opacity-0 group-hover:opacity-100"
                                >
                                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                  </svg>
                                </button>
                              </div>
                              <div className="grid grid-cols-2 gap-3 text-xs">
                                {[
                                  { label: "Slot Skips", value: item.slot },
                                  { label: "Top Slot Skipper", value: sDisplay },
                                  { label: "UPC Skips", value: item.upc },
                                  { label: "Top UPC Skipper", value: uDisplay },
                                ].map((d) => (
                                  <div
                                    key={d.label}
                                    className="p-2 rounded bg-slate-800/50 border border-slate-700 text-center"
                                  >
                                    <div className="text-[9px] text-slate-400 uppercase font-bold mb-0.5">
                                      {d.label}
                                    </div>
                                    <div className="font-bold text-white text-xs truncate">
                                      {d.value}
                                    </div>
                                  </div>
                                ))}
                              </div>
                            </div>
                          );
                        })}
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
