export const FACTORY_ADDRESS = "0xE01FE1C2A22736da756BDc2C9144464E8A73fCd7";
export const RPC_URL = "https://mainnet.infura.io/v3/cf2916fb6dbc47ae824d6f36db817b73";

export const factoryAbi = [
  {
    inputs: [],
    name: "FEE_RECIPIENT_1",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FEE_RECIPIENT_2",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "refundPercentage", type: "uint256" },
      { internalType: "address[]", name: "feeReceivers", type: "address[]" },
      { internalType: "uint256[]", name: "feeReceiverPercentages", type: "uint256[]" },
      { internalType: "uint256", name: "startingBidWei", type: "uint256" },
      { internalType: "uint256", name: "minBidIncrementWei", type: "uint256" },
      { internalType: "uint256", name: "signFeeWei", type: "uint256" },
      { internalType: "uint256", name: "maxSignerLength", type: "uint256" },
      { internalType: "address", name: "bidPaymentToken", type: "address" },
      { internalType: "uint256", name: "adlockDuration", type: "uint256" },
    ],
    name: "deployAuctionContract",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getFactoryOverview",
    outputs: [
      {
        components: [
          { internalType: "address", name: "contractAddress", type: "address" },
          { internalType: "uint256", name: "refundPercentage", type: "uint256" },
          { internalType: "address[]", name: "feeReceivers", type: "address[]" },
          { internalType: "uint256[]", name: "feeReceiverPercentages", type: "uint256[]" },
          { internalType: "uint256", name: "startingBidWei", type: "uint256" },
          { internalType: "uint256", name: "minBidIncrementWei", type: "uint256" },
          { internalType: "uint256", name: "signFeeWei", type: "uint256" },
          { internalType: "uint256", name: "maxSignerLength", type: "uint256" },
          { internalType: "address", name: "bidPaymentToken", type: "address" },
          { internalType: "uint256", name: "adlockDuration", type: "uint256" },
        ],
        internalType: "struct AdAuctionFactory.AuctionContractInfo[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "contractAddress", type: "address" },
      { indexed: true, internalType: "address", name: "creator", type: "address" },
      { indexed: false, internalType: "uint256", name: "refundPercentage", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "startingBidWei", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "minBidIncrementWei", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "signFeeWei", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "maxSignerLength", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "adlockDuration", type: "uint256" },
    ],
    name: "AuctionContractDeployed",
    type: "event",
  },
] as const;

export const auctionAbi = [
  {
    inputs: [],
    name: "adlockDuration",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "bidPaymentToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentAdURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentHighestBid",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentHighestBidder",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "deleteAllSigners",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getAuctionDetails",
    outputs: [
      { internalType: "address", name: "bidder", type: "address" },
      { internalType: "uint256", name: "bid", type: "uint256" },
      { internalType: "string", name: "adURI", type: "string" },
      { internalType: "uint256", name: "totalBidsCount", type: "uint256" },
      { internalType: "uint256", name: "signFee", type: "uint256" },
      { internalType: "uint256", name: "maxSignerLen", type: "uint256" },
      { internalType: "address", name: "signToken", type: "address" },
      { internalType: "uint256", name: "adlockDurationSeconds", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSigners",
    outputs: [
      {
        components: [
          { internalType: "address", name: "signerAddress", type: "address" },
          { internalType: "string", name: "signerName", type: "string" },
          { internalType: "uint256", name: "timestamp", type: "uint256" },
        ],
        internalType: "struct AdAuctionContract.Signer[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lastBidTimestamp",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxSignerLength",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minBidIncrementWei",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "adURI", type: "string" },
      { internalType: "uint256", name: "bidAmount", type: "uint256" },
    ],
    name: "placeBid",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "refundPercentage",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "signerName", type: "string" }],
    name: "signAd",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "signFeeWei",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "signPaymentToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalBids",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_newSignFeeWei", type: "uint256" },
      { internalType: "uint256", name: "_newMaxSignerLength", type: "uint256" },
    ],
    name: "updateSignParameters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_newSignPaymentToken", type: "address" }],
    name: "updateSignPaymentToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;

export const erc20Abi = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function balanceOf(address) view returns (uint256)",
  "function approve(address,uint256) returns (bool)",
  "function allowance(address,address) view returns (uint256)",
  "function transfer(address,uint256) returns (bool)",
];
